# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

blank_issues_enabled: true
contact_links:
  - name: 🗂️ Assets README
    url: https://github.com/ultralytics/assets#readme
    about: Overview of logos, datasets, and model files
  - name: 💬 Forum
    url: https://community.ultralytics.com
    about: Ask the Ultralytics community for workflow help
  - name: 🎧 Discord
    url: https://ultralytics.com/discord
    about: Chat with the Ultralytics team and other builders
  - name: ⌨️ Reddit
    url: https://www.reddit.com/r/ultralytics/
    about: Discuss Ultralytics projects on Reddit
